#!/usr/bin/env bash
# Expand canonical Claude allowances against CLI help; validate before replacing.
set -euo pipefail
cd "$(dirname "$0")"
python3 - <<'PY'
import fnmatch
import json
import os
from pathlib import Path
import re
import subprocess
import tempfile

def run(argv):
    return subprocess.run(argv, check=True, text=True, capture_output=True,
                          env={**os.environ, "AWS_PAGER": "", "PAGER": "cat"}).stdout

try:
    allowances = json.loads(Path('../../.claude/settings.json').read_text())['permissions']['allow']
    patterns = {}
    for entry in allowances:
        if not entry.startswith('Bash(aws '):
            continue
        # Prefixes cannot constrain copy destinations. Never widen this form.
        if entry == 'Bash(aws s3 cp s3://* -)':
            continue
        if entry == 'Bash(aws help *)':
            continue  # Already covered by default.rules.
        match = re.fullmatch(r'Bash\(aws ([a-z0-9-]+) ([a-z0-9-]+\*?)(?: \*)?\)', entry)
        if not match:
            raise ValueError(f'Unsupported AWS allowance: {entry}')
        service, pattern = match.groups()
        patterns.setdefault(service, set()).add(pattern)
    if not patterns:
        raise ValueError('No canonical AWS allowances found')

    lines = ['# GENERATED by generate-aws-read.sh; do not hand-edit.',
             '# Exact operations from canonical Claude allowances and installed AWS CLI help.',
             '# Other commands remain reviewable; secret-value hooks still deny.', '']
    for service, globs in sorted(patterns.items()):
        help_text = run(['aws', service, 'help'])
        help_text = subprocess.run(['col', '-b'], input=help_text, text=True,
                                   capture_output=True, check=True).stdout
        section = help_text.split('AVAILABLE COMMANDS', 1)
        if len(section) != 2:
            raise ValueError(f'No AVAILABLE COMMANDS in {service} help')
        available = set(re.findall(r'^\s+o ([a-z0-9-]+)\s*$', section[1], re.M))
        selected = set()
        for pattern in sorted(globs):
            matches = {op for op in available if fnmatch.fnmatchcase(op, pattern)}
            if not matches:
                raise ValueError(f'No operations match aws {service} {pattern}')
            selected.update(matches)
        var = 'AWS_' + service.upper().replace('-', '_') + '_READ_OPS'
        lines += [var + ' = ['] + [f'    "{op}",' for op in sorted(selected)]
        lines += [']', '', 'prefix_rule(', f'    pattern = ["aws", "{service}", {var}],',
                  '    decision = "allow",',
                  '    justification = "Exact operation parity with canonical Claude allowances.",',
                  ')', '']

    temporary = None
    try:
        with tempfile.NamedTemporaryFile(mode='w', dir='.', prefix='.aws-read-', suffix='.rules', delete=False) as f:
            temporary = Path(f.name)
            f.write('\n'.join(lines))
        run(['codex', 'execpolicy', 'check', '--rules', str(temporary), 'aws', 'sts', 'get-caller-identity'])
        temporary.chmod(0o644)
        temporary.replace('aws-read.rules')
    finally:
        if temporary is not None:
            temporary.unlink(missing_ok=True)
    print(f'wrote aws-read.rules ({len(patterns)} services)')
except (ValueError, KeyError, OSError, subprocess.CalledProcessError) as exc:
    raise SystemExit(f'AWS rule generation failed; existing output preserved: {exc}')
PY
