#!/usr/bin/env bash
# Regenerates aws-read.rules: per-op allow rules for the AWS services actually
# in use, derived from the installed AWS CLI. Writes and unlisted services fall
# through to Codex's approval prompt. Rerun after `aws` upgrades or when adding
# a service, then commit the result.
set -euo pipefail

cd "$(dirname "$0")"

# Services observed in real usage (Claude session transcripts + shell history).
# sts is handled separately: get-* would include credential-minting ops
# (get-session-token, get-federation-token) that Claude does not allow either.
SERVICES=(amplify ce cloudfront iam logs route53 route53domains ses sesv2 wafv2)

READ_OP_REGEX='^(describe-|list-|get-|head-|batch-get-|transact-get-|search-|select-|simulate-|check-)|^(scan|query|tail|filter-log-events|start-query|stop-query|test-dns-answer|view-billing|decode-authorization-message|download-db-log-file-portion)$'

OUT=aws-read.rules
{
  echo "# GENERATED by generate-aws-read.sh from 'aws <service> help' — do not hand-edit."
  echo "# Read ops for actively used AWS services auto-allow; every other AWS command"
  echo "# (writes, unlisted services) falls through to Codex's approval prompt."
  echo "# aws-readonly-check.sh still hard-denies secretsmanager secret-value reads."
  echo
  for s in "${SERVICES[@]}"; do
    var="AWS_$(echo "$s" | tr '[:lower:]-' '[:upper:]_')_READ_OPS"
    ops=$(aws "$s" help 2>/dev/null | col -b | sed -n '/AVAILABLE COMMANDS/,$p' |
      awk '/^       o [a-z0-9-]+$/ {print $2}' | grep -E "$READ_OP_REGEX" || true)
    [ -n "$ops" ] || { echo "no read ops found for '$s' — is the AWS CLI installed?" >&2; exit 1; }
    echo "$var = ["
    while IFS= read -r op; do echo "    \"$op\","; done <<< "$ops"
    echo "]"
    echo
    echo "prefix_rule("
    echo "    pattern = [\"aws\", \"$s\", $var],"
    echo "    decision = \"allow\","
    echo "    justification = \"Read parity with Claude's allowlist for actively used services.\","
    echo ")"
    echo
  done
  cat <<'EOF'
prefix_rule(
    pattern = ["aws", "sts", ["get-caller-identity", "get-access-key-info", "decode-authorization-message"]],
    decision = "allow",
    justification = "Exactly the sts reads Claude allows; get-session-token/get-federation-token mint credentials and must prompt.",
)

prefix_rule(
    pattern = ["aws", "configure", ["list", "list-profiles", "get"]],
    decision = "allow",
    justification = "Local config inspection; 'aws configure set' falls through to prompt.",
)
EOF
} > "$OUT"

echo "wrote $OUT ($(grep -c '"' "$OUT") quoted tokens)" >&2
